version: '2'
services:
    jhipsterplay-app:
        image: jhipsterplay
        external_links:
            - jhipsterplay-mysql:mysql
            - jhipsterplay-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipsterplay?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterplay-mysql:
        extends:
            file: mysql.yml
            service: jhipsterplay-mysql
    jhipsterplay-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterplay-elasticsearch
